import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home</title>
      </Head>
      <h1 className='text-3xl text-red-400'>Testing</h1>
      
    </div>
  )
}
